version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y build-essential docutils hugo python-openssl

      - run:
          name: Deploy
          command: |
            export CLOUDSDK_PYTHON_SITEPACKAGES=1

            echo "$GCLOUD_SERVICE_KEY" | \
              gcloud auth activate-service-account \
                circleci-radiclexyz-uploader@opensourcecoin.iam.gserviceaccount.com \
                --key-file=-

            make deploy
