version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            set -ex

            apt-get update
            apt-get install -y build-essential python-docutils python-openssl wget

            wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_extended_0.54.0_Linux-64bit.deb
            dpkg -i hugo*.deb

            hugo version

      - run:
          name: Deploy
          command: |
            set -ex

            export CLOUDSDK_PYTHON_SITEPACKAGES=1

            echo "$GCLOUD_SERVICE_KEY" | \
              gcloud auth activate-service-account \
                circleci-radiclexyz-uploader@opensourcecoin.iam.gserviceaccount.com \
                --key-file=-

            make deploy
