version: 2.1

executors:
  cloud-sdk:
    docker:
      - image: google/cloud-sdk
    working_directory: /tmp

jobs:
  build:
    executor: cloud-sdk
    steps:
      - checkout

      - run:
          name: Install Dependencies
          environment:
            HUGO_VERSION: 0.54.0
          command: |
            set -ex

            apt-get update
            apt-get install -y build-essential python-docutils python-openssl wget

            wget "https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb"
            apt-get install "./hugo_extended_${HUGO_VERSION}_Linux-64bit.deb"
            dpkg -i hugo*.deb

            make build

      - persist_to_workspace:
        root: /tmp


  deploy:
    executor: cloud-sdk
    steps:
      - attach_workspace:
        at: /tmp

      - run: |
          set -ex

          export CLOUDSDK_PYTHON_SITEPACKAGES=1

          echo "$GCLOUD_SERVICE_KEY" | \
            gcloud auth activate-service-account \
              circleci-radiclexyz-uploader@opensourcecoin.iam.gserviceaccount.com \
              --key-file=-

          make deploy

workflows:
  version: 2.1
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
        # filters:
        #   branches:
        #     only:
        #       - master
