version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk

    steps:
      - checkout

      - run:
          name: Install Hugo
          command: |
            apt-get update
            apt-get install -y hugo

      - run:
          name: Install docutils
          command: |
            set -ex

            pip install docutils

      - run:
          name: Deploy
          command: |
            export CLOUDSDK_PYTHON_SITEPACKAGES=1

            apt-get install -y --force-yes python-openssl

            echo "$GCLOUD_SERVICE_KEY" | \
              gcloud auth activate-service-account \
                circleci-radiclexyz-uploader@opensourcecoin.iam.gserviceaccount.com \
                --key-file=-

            make deploy
