version: 2

# Environment shared between jobs.
defaults: &defaults
  environment:
    HUGO_VERSION: 0.54.0
  docker:
    - image: google/cloud-sdk

# Use reference to avoid duplication for dependency setup.
_run:
  dependencies: &dependencies
    command: |-
      set -ex

      apt-get update
      apt-get install -y build-essential python-docutils python-openssl wget

      wget "https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb"
      apt-get install "./hugo_extended_${HUGO_VERSION}_Linux-64bit.deb"
      dpkg -i hugo*.deb

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: *dependencies
      - run: make build

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: *dependencies
      - run: |-
          set -ex

          export CLOUDSDK_PYTHON_SITEPACKAGES=1

          echo "$GCLOUD_SERVICE_KEY" | \
            gcloud auth activate-service-account \
              circleci-radiclexyz-uploader@opensourcecoin.iam.gserviceaccount.com \
              --key-file=-

          make deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
        # filters:
        #   branches:
        #     only:
        #       - master
